# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Casper Kaae Sønderby
tagline:             'A Machine Learning Researcher '
description:         'Machine learning researcher interested in baysian learning and Deep Learning'
url:                 casperkaae.github.io
baseurl:             ''
paginate:            5


collections:
  publications:
    output: true

# About/contact
author:
  name:              Casper Kaae Sønderby
  url:               https://casperkaae.github.com/
  email:             casperkaae@gmail.com

# Custom vars
version:             1.0.0
